import { nanoid } from "nanoid";

const notes = [
  {
    id: nanoid(),
    title: "Midterm FOC",
    text: "exam.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "1",
  },
  {
    id: nanoid(),
    title: "Midterm AFC",
    text: "exam.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "1",
  },
  {
    id: nanoid(),
    title: "Midterm FOC",
    text: "exam.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "2",
  },
  {
    id: nanoid(),
    title: "Midterm AFC",
    text: "exam.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "2",
  },
  {
    id: nanoid(),
    title: "Final exam",
    text: "exam.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "2",
  },
  {
    id: nanoid(),
    title: "Final exam",
    text: "exam.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "2",
  },
  {
    id: nanoid(),
    title: "Assignment 1",
    text: "e-learning.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "3",
  },
  {
    id: nanoid(),
    title: "Assignment 2",
    text: "e-learning.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "3",
  },
  {
    id: nanoid(),
    title: "Assignment 3",
    text: "e-learning.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "3",
  },
  {
    id: nanoid(),
    title: "Assigment 4",
    text: "e-learning.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "3",
  },
  {
    id: nanoid(),
    title: "Assignment 5",
    text: "e-learning.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "3",
  },
  {
    id: nanoid(),
    title: "Assignment 6",
    text: "e-learning.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "3",
  },
  {
    id: nanoid(),
    title: "Assignment 7",
    text: "e-learning.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "3",
  },
  {
    id: nanoid(),
    title: "Assignment 8",
    text: "e-learning.hcmut.edu.vn",
    content: "target 10",
    date: "October 26th 2021",
    time: "04:30",
    tag: "exam",
    color: "#000000",
    type: "3",
  },
];

export default notes;
